### ISSUE TITLE
directiories.data in custom arduino-cli instalation's arduino-cli.yaml not used

### ISSUE THREAD

**Issue by milanbx** [vscode-arduino/vscode-arduino#60]
Hi!
## Environment
I am running portable VSCode v1.96.3 on Windows and custom `arduino-cli` instalation. `ARDUINO_CONFIG_FILE` Windows environment variable is set to point to custom `arduino-cli` configuration file:
`ARDUINO_CONFIG_FILE = D:\Portable\ArduinoCLI\arduino-cli.yaml`.
This YAML configuration sets the `directiories.data` parameter to custom `arduino-cli`instalation root, where all JSON library indexes and packages' files are stored:
```yaml
board_manager:
    additional_urls:
        - http://arduino.esp8266.com/stable/package_esp8266com_index.json
        - https://espressif.github.io/arduino-esp32/package_esp32_index.json
        - https://mcudude.github.io/MiniCore/package_MCUdude_MiniCore_index.json
        - https://drazzy.com/package_drazzy.com_index.json
directories:
    builtin:
        libraries: d:\Portable\ArduinoCLI\libraries
    data: d:\Portable\ArduinoCLI

```

## Problem
When compiling sketch in Code, the custom configuration file `arduino-cli.yaml` is not used (not read), which leads to error, where no package/board libs are found and compilation doesn't even start, because no board is selected.

## Workarround
Defining another Windows environment variable `ARDUINO_DIRECTORIES_DATA` with value `D:\Portable\ArduinoCLI` solves this:
`ARDUINO_DIRECTORIES_DATA = D:\Portable\ArduinoCLI`

## Remarks
When `ARDUINO_DIRECTORIES_DATA` is set, you should close Code and start over to use it.
